"""Interfaces the services depend on, implemented by the adapters."""

from collections.abc import AsyncIterator
from datetime import datetime, timedelta
from pathlib import Path
from typing import Literal, Protocol
from uuid import UUID

from babel_api.domain.catalog import (
    CoverImage,
    Edition,
    IdentifierKind,
    SourceEdition,
    SourceWork,
    TrendingWork,
    Work,
)
from babel_api.domain.files import BookFormat, BookMetadata, LibraryItem, StoredFile
from babel_api.domain.mail import EmailMessage
from babel_api.domain.users import (
    AccountToken,
    ExternalIdentity,
    IdentityProvider,
    RefreshToken,
    TokenPurpose,
    User,
)


class UserRepository(Protocol):
    """Persistence of users, identities and refresh tokens."""

    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_identity(self, provider: IdentityProvider, subject: str) -> User | None: ...
    async def add(
        self, email: str, display_name: str, password_hash: str | None, locale: str = "fr"
    ) -> User: ...
    async def link_identity(
        self, user_id: UUID, provider: IdentityProvider, subject: str
    ) -> None: ...
    async def update(
        self,
        user_id: UUID,
        *,
        display_name: str | None = None,
        password_hash: str | None = None,
        locale: str | None = None,
        email_verified_at: datetime | None = None,
    ) -> User: ...
    async def clear_password(self, user_id: UUID) -> None: ...
    async def delete(self, user_id: UUID) -> None: ...

    async def add_refresh_token(self, token: RefreshToken) -> None: ...
    async def get_refresh_token(self, token_id: UUID) -> RefreshToken | None: ...
    async def revoke_refresh_token(self, token_id: UUID, at: datetime) -> None: ...
    async def revoke_refresh_family(self, family_id: UUID, at: datetime) -> None: ...
    async def revoke_user_refresh_tokens(self, user_id: UUID, at: datetime) -> None: ...

    async def add_account_token(self, token: AccountToken) -> None: ...
    async def get_account_token(self, token_id: UUID) -> AccountToken | None: ...
    async def last_account_token(self, user_id: UUID, purpose: TokenPurpose) -> datetime | None: ...
    async def use_account_tokens(
        self, user_id: UUID, purpose: TokenPurpose, at: datetime
    ) -> None: ...

    async def commit(self) -> None: ...


class PasswordHasher(Protocol):
    """One-way password hashing."""

    def hash(self, password: str) -> str: ...
    def verify(self, password_hash: str, password: str) -> bool: ...
    def needs_rehash(self, password_hash: str) -> bool: ...


class IdentityVerifier(Protocol):
    """Verifies an identity-provider ID token and returns its claims."""

    @property
    def enabled(self) -> bool: ...
    async def verify(self, id_token: str, nonce: str | None) -> ExternalIdentity: ...


class AccessTokens(Protocol):
    """Issues short-lived access tokens."""

    @property
    def ttl(self) -> timedelta: ...
    def issue(self, user_id: UUID, now: datetime | None = None) -> str: ...


CoverSize = Literal["S", "M", "L"]


class TrendingSource(Protocol):
    """Popular works and cover images of an external catalog."""

    async def trending(self, limit: int) -> list[TrendingWork]: ...
    async def cover(self, cover_id: int, size: CoverSize) -> CoverImage | None: ...


class BookSource(Protocol):
    """Work and edition records of an external catalog (Open Library, Google Books…)."""

    async def search(
        self, query: str, limit: int, language: str | None = None
    ) -> list[SourceWork]: ...
    async def work(self, open_library_id: str) -> SourceWork | None: ...
    async def editions(self, work_open_library_id: str, limit: int) -> list[SourceEdition]: ...
    async def edition_by_isbn(self, isbn13: str) -> SourceEdition | None: ...


class CatalogRepository(Protocol):
    """Persistence of works and editions fetched from external catalogs."""

    async def upsert_work(self, work: SourceWork) -> Work: ...
    async def get_work(self, work_id: UUID) -> Work | None: ...
    async def get_work_by_open_library_id(self, open_library_id: str) -> Work | None: ...
    async def upsert_editions(self, work_id: UUID, editions: list[SourceEdition]) -> None: ...
    async def list_editions(self, work_id: UUID) -> list[Edition]: ...
    async def find_edition(self, kind: IdentifierKind, value: str) -> Edition | None: ...
    async def mark_editions_synced(self, work_id: UUID, at: datetime) -> None: ...
    async def commit(self) -> None: ...


class Mailer(Protocol):
    """Sends emails. Implementations must not raise: failures are logged."""

    async def send(self, message: EmailMessage) -> None: ...


class BlobStore(Protocol):
    """Content-addressed storage of file bytes."""

    async def put(self, chunks: AsyncIterator[bytes], max_bytes: int) -> tuple[str, int, Path]:
        """Store the content, return its SHA-256, size and local path. Deduplicates."""
        ...

    def path(self, sha256: str) -> Path | None: ...
    async def delete(self, sha256: str) -> None: ...


class FileRepository(Protocol):
    """Stored files, blocked hashes and library items."""

    async def get_file(self, sha256: str) -> StoredFile | None: ...
    async def add_file(self, file: StoredFile) -> None: ...
    async def withdraw_file(self, sha256: str, at: datetime) -> None: ...
    async def reinstate_file(self, sha256: str, uploaded_by: UUID) -> None: ...
    async def is_blocked(self, sha256: str) -> bool: ...
    async def block(self, sha256: str, reason: str, by: UUID | None, at: datetime) -> None: ...
    async def add_item(
        self, user_id: UUID, sha256: str, title: str, authors: tuple[str, ...]
    ) -> LibraryItem: ...
    async def find_item(self, user_id: UUID, sha256: str) -> LibraryItem | None: ...
    async def get_item(self, item_id: UUID) -> LibraryItem | None: ...
    async def list_items(self, user_id: UUID) -> list[LibraryItem]: ...
    async def delete_item(self, item_id: UUID) -> None: ...
    async def delete_items_of_file(self, sha256: str) -> None: ...
    async def commit(self) -> None: ...


class MetadataReader(Protocol):
    """Detects the format of a file and reads the metadata it embeds."""

    def detect(self, path: Path) -> BookFormat | None: ...
    def metadata(self, path: Path, file_format: BookFormat) -> BookMetadata: ...
