"""Interfaces the services depend on, implemented by the adapters."""

from collections.abc import AsyncIterator
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Literal, Protocol
from uuid import UUID

from babel_api.domain.catalog import (
    CoverImage,
    Edition,
    IdentifierKind,
    SourceEdition,
    SourceWork,
    TrendingWork,
    Work,
)
from babel_api.domain.files import BookFormat, BookMetadata, Cover, LibraryItem, StoredFile
from babel_api.domain.mail import EmailMessage
from babel_api.domain.sources import RemoteEntry, Source, SourceEntry, SourceKind
from babel_api.domain.sync import (
    Change,
    ChangeOp,
    Device,
    DeviceKind,
    EntityKind,
    ReadingPosition,
)
from babel_api.domain.users import (
    AccountToken,
    ExternalIdentity,
    IdentityProvider,
    RefreshToken,
    TokenPurpose,
    User,
)


class UserRepository(Protocol):
    """Persistence of users, identities and refresh tokens."""

    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_identity(self, provider: IdentityProvider, subject: str) -> User | None: ...
    async def add(
        self, email: str, display_name: str, password_hash: str | None, locale: str = "fr"
    ) -> User: ...
    async def link_identity(
        self, user_id: UUID, provider: IdentityProvider, subject: str
    ) -> None: ...
    async def update(
        self,
        user_id: UUID,
        *,
        display_name: str | None = None,
        password_hash: str | None = None,
        locale: str | None = None,
        email_verified_at: datetime | None = None,
    ) -> User: ...
    async def clear_password(self, user_id: UUID) -> None: ...
    async def delete(self, user_id: UUID) -> None: ...

    async def add_refresh_token(self, token: RefreshToken) -> None: ...
    async def get_refresh_token(self, token_id: UUID) -> RefreshToken | None: ...
    async def revoke_refresh_token(self, token_id: UUID, at: datetime) -> None: ...
    async def revoke_refresh_family(self, family_id: UUID, at: datetime) -> None: ...
    async def revoke_user_refresh_tokens(self, user_id: UUID, at: datetime) -> None: ...

    async def add_account_token(self, token: AccountToken) -> None: ...
    async def get_account_token(self, token_id: UUID) -> AccountToken | None: ...
    async def last_account_token(self, user_id: UUID, purpose: TokenPurpose) -> datetime | None: ...
    async def use_account_tokens(
        self, user_id: UUID, purpose: TokenPurpose, at: datetime
    ) -> None: ...

    async def commit(self) -> None: ...


class PasswordHasher(Protocol):
    """One-way password hashing."""

    def hash(self, password: str) -> str: ...
    def verify(self, password_hash: str, password: str) -> bool: ...
    def needs_rehash(self, password_hash: str) -> bool: ...


class IdentityVerifier(Protocol):
    """Verifies an identity-provider ID token and returns its claims."""

    @property
    def enabled(self) -> bool: ...
    async def verify(self, id_token: str, nonce: str | None) -> ExternalIdentity: ...


class AccessTokens(Protocol):
    """Issues short-lived access tokens."""

    @property
    def ttl(self) -> timedelta: ...
    def issue(self, user_id: UUID, now: datetime | None = None) -> str: ...


CoverSize = Literal["S", "M", "L"]


class TrendingSource(Protocol):
    """Popular works and cover images of an external catalog."""

    async def trending(self, limit: int) -> list[TrendingWork]: ...
    async def cover(self, cover_id: int, size: CoverSize) -> CoverImage | None: ...


class BookSource(Protocol):
    """Work and edition records of an external catalog (Open Library, Google Books…)."""

    async def search(
        self, query: str, limit: int, language: str | None = None
    ) -> list[SourceWork]: ...
    async def work(self, open_library_id: str) -> SourceWork | None: ...
    async def editions(self, work_open_library_id: str, limit: int) -> list[SourceEdition]: ...
    async def edition_by_isbn(self, isbn13: str) -> SourceEdition | None: ...


class CatalogRepository(Protocol):
    """Persistence of works and editions fetched from external catalogs."""

    async def upsert_work(self, work: SourceWork) -> Work: ...
    async def get_work(self, work_id: UUID) -> Work | None: ...
    async def get_work_by_open_library_id(self, open_library_id: str) -> Work | None: ...
    async def upsert_editions(self, work_id: UUID, editions: list[SourceEdition]) -> None: ...
    async def list_editions(self, work_id: UUID) -> list[Edition]: ...
    async def find_edition(self, kind: IdentifierKind, value: str) -> Edition | None: ...
    async def mark_editions_synced(self, work_id: UUID, at: datetime) -> None: ...
    async def commit(self) -> None: ...


class Mailer(Protocol):
    """Sends emails. Implementations must not raise: failures are logged."""

    async def send(self, message: EmailMessage) -> None: ...


class BlobStore(Protocol):
    """Content-addressed storage of file bytes."""

    async def put(self, chunks: AsyncIterator[bytes], max_bytes: int) -> tuple[str, int, Path]:
        """Store the content, return its SHA-256, size and local path. Deduplicates."""
        ...

    def path(self, sha256: str) -> Path | None: ...
    async def delete(self, sha256: str) -> None: ...


class FileRepository(Protocol):
    """Stored files, blocked hashes and library items."""

    async def get_file(self, sha256: str) -> StoredFile | None: ...
    async def add_file(self, file: StoredFile) -> None: ...
    async def withdraw_file(self, sha256: str, at: datetime) -> None: ...
    async def reinstate_file(self, sha256: str, uploaded_by: UUID) -> None: ...
    async def is_blocked(self, sha256: str) -> bool: ...
    async def block(self, sha256: str, reason: str, by: UUID | None, at: datetime) -> None: ...
    async def add_item(
        self, user_id: UUID, sha256: str, title: str, authors: tuple[str, ...]
    ) -> LibraryItem: ...
    async def find_item(self, user_id: UUID, sha256: str) -> LibraryItem | None: ...
    async def get_item(self, item_id: UUID) -> LibraryItem | None: ...
    async def list_items(self, user_id: UUID) -> list[LibraryItem]: ...
    async def delete_item(self, item_id: UUID) -> None: ...
    async def items_of_file(self, sha256: str) -> list[LibraryItem]: ...
    async def delete_items_of_file(self, sha256: str) -> None: ...
    async def commit(self) -> None: ...


class MetadataReader(Protocol):
    """Detects the format of a file and reads the metadata it embeds."""

    def detect(self, path: Path) -> BookFormat | None: ...
    def metadata(self, path: Path, file_format: BookFormat) -> BookMetadata: ...
    def cover(self, path: Path, file_format: BookFormat) -> Cover | None: ...


class CoverCache(Protocol):
    """Covers extracted from stored files, kept so each file is opened once."""

    def get(self, sha256: str) -> tuple[Path, str] | Literal[False] | None:
        """The cover (path, media type), False when the file has none, None when unknown."""
        ...

    def put(self, sha256: str, cover: Cover | None) -> tuple[Path, str] | None: ...


class ChangeLog(Protocol):
    """Appends to a user's change log. Written in the same transaction as the change."""

    async def record(
        self,
        user_id: UUID,
        entity: EntityKind,
        entity_id: str,
        op: ChangeOp,
        data: dict[str, Any] | None = None,
        device_id: UUID | None = None,
    ) -> int: ...


class SyncRepository(ChangeLog, Protocol):
    """Devices, change log reads, applied operations and reading positions."""

    async def add_device(self, user_id: UUID, name: str, kind: DeviceKind) -> Device: ...
    async def get_device(self, device_id: UUID) -> Device | None: ...
    async def list_devices(self, user_id: UUID) -> list[Device]: ...
    async def touch_device(self, device_id: UUID, at: datetime) -> None: ...
    async def delete_device(self, device_id: UUID) -> None: ...

    async def changes_since(self, user_id: UUID, seq: int, limit: int) -> list[Change]: ...
    async def latest_seq(self, user_id: UUID) -> int: ...

    async def applied(self, user_id: UUID, key: str) -> bool: ...
    async def mark_applied(self, user_id: UUID, key: str, at: datetime) -> None: ...

    async def get_position(self, item_id: UUID, device_id: UUID) -> ReadingPosition | None: ...
    async def save_position(self, user_id: UUID, position: ReadingPosition) -> None: ...
    async def list_positions(self, item_id: UUID) -> list[ReadingPosition]: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class SourceConnector(Protocol):
    """Reads one kind of source. Read-only: it never writes to the source."""

    async def check(self, config: dict[str, Any], token: str | None) -> dict[str, Any]:
        """Validate access; return the config completed with what was learned (branch…)."""
        ...

    async def list_entries(
        self, config: dict[str, Any], token: str | None
    ) -> list[RemoteEntry]: ...

    def fetch(
        self, config: dict[str, Any], token: str | None, entry: RemoteEntry
    ) -> AsyncIterator[bytes]: ...


class SourceRepository(Protocol):
    async def add(
        self,
        user_id: UUID,
        kind: SourceKind,
        name: str,
        config: dict[str, Any],
        encrypted_token: str | None,
    ) -> Source: ...
    async def get(self, source_id: UUID) -> Source | None: ...
    async def encrypted_token(self, source_id: UUID) -> str | None: ...
    async def list_sources(self, user_id: UUID) -> list[Source]: ...
    async def count(self, user_id: UUID) -> int: ...
    async def delete(self, source_id: UUID) -> None: ...
    async def record_scan(
        self, source_id: UUID, entries: list[RemoteEntry], at: datetime, error: str | None
    ) -> None: ...
    async def entries(self, source_id: UUID) -> list[SourceEntry]: ...
    async def get_entry(self, entry_id: UUID) -> SourceEntry | None: ...
    async def mark_unreadable(self, entry_id: UUID) -> None: ...
    async def known_file(self, kind: SourceKind, remote_id: str) -> str | None: ...
    async def remember_file(self, kind: SourceKind, remote_id: str, sha256: str) -> None: ...
    async def commit(self) -> None: ...
